### ISSUE TITLE
Please add UTF8 support

### ISSUE THREAD

**Issue by LauLaman** [api-postcode/api-postcode-bundle#3]
When requesting address  information containing UTF-8 characters the API does not encode UTF-8 

> **Input data**
> zipcode: 1336 CE
> number: 4

Raw data from curl:
```
{
	"street": "Itali\u00c3\u00abstraat",
	"postcode": "1363CE",
	"house_number": "4",
	"city": "Almere",
	"longitude": "5.1489675",
	"latitude": "52.3459343",
	"province": "Flevoland"
}
```

Which gets converted to array:
```
[
  "street" => "ItaliÃ«straat"
  "postcode" => "1363CE"
  "house_number" => "4"
  "city" => "Almere"
  "longitude" => "5.1489675"
  "latitude" => "52.3459343"
  "province" => "Flevoland"
]
```

Which is correct because the server sends the encoding for `Ã«` back

**Comment by LauLaman** [comment]
ping @Shivella :)

**Comment by Shivella** [comment]
Thanks @LauLaman for keep this issue under attention.
The fix has been done on server side and the longitude and latitude now return a float instead of string.

Please let me know if you run into any issue!

**Comment by LauLaman** [comment]
Held 👍
