### ISSUE TITLE
Latitude and longitude of the postcode api are reversed

### ISSUE THREAD

**Issue by GitMarJansen** [api-postcode/api-postcode-bundle#5]
When using the sample address, I get a latlong which is invalid. It appears the values of latitude and longitude are reversed. Cannot find where to report the api-issue.
GET: http://json.api-postcode.nl?postcode=1012JS&number=1
result: {
    "city": "Amsterdam",
    "street": "Dam",
    "house_number": "1",
    "postcode": "1012JS",
    "province": "Noord-Holland",
    "longitude": 52.3732926,
    "latitude": 4.8937175
}

Should be 
...
    "latitude": 52.3732926,
    "longitude": 4.8937175
}

**Comment by Shivella** [comment]
Should be fixed now.
